### ISSUE TITLE
may I jion the dokan-java group

### ISSUE THREAD

**Issue by hukeowen** [dokan-dev/dokan-java#16]
I'm a java development,I'm very happy the dokan-java code is update,But I Found there is not still implement the whole function,such as oncreate ondele and so on.
The dokan.exe is very fasy to copy little file,But dokan java is very slow,dokan java only has 18kb/s,if the file size is 4kb,but dokan.exe can run 200kb/s speed

**Comment by infeo** [comment]
To contribute you don't have to be part of the dokan-java group, just make a fork and start programming! If you think you're done make a pullrequest to this repository, i review it and will finally merge it into the development branch (;

I don't know which functions do you mean with "onCreate" or "onDelete".
The dokan-java project just implements a java-interface for the dokany-api, and thus it just must access/implement some internal functions of dokan, the api itself must stay unimplemented.

Regarding the speed, i think this is mostly because this project uses JNA. It has a clean, easy and good interface to work with, but lacks speed. There are other projects to call native code from java (e.g. [JNR](https://github.com/jnr/jnr-ffi)), which can be used to replace JNA.
